server:
  port: 8080

spring:
  application:
    name: weather-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: "true"

info:
  app:
    name: "weather-service"
    description: "Get fast and easy access to the world's most accurate
weather, ocean, environment and climate data for every location on
earth."
    version: "1.0.0"